version: 0.2

phases:
  install:
    commands:
      - echo "Downloading Node 20 binary..."
      - curl -o node.tar.xz https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-x64.tar.xz
      - echo "Extracting Node..."
      - tar -xf node.tar.xz
      - echo "Adding Node to PATH..."
      - export PATH=$PWD/node-v20.10.0-linux-x64/bin:$PATH
      - node -v
      - npm -v
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Running Next.js static build..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: out
