version: 0.2

phases:
  install:
    commands:
      - echo "Resetting Node.js module..."
      - dnf module reset nodejs -y
      - echo "Enabling Node.js 20 module..."
      - dnf module enable nodejs:20 -y
      - echo "Installing Node.js 20..."
      - dnf install -y nodejs
      - echo "Verifying Node version..."
      - node -v
      - npm -v
      - echo "Installing project dependencies..."
      - npm install

  build:
    commands:
      - echo "Building Next.js static export..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: out
